CREATE TABLE IF NOT EXISTS users
(
    id INTEGER PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    pass_hash BLOB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users(email); 

CREATE TABLE IF NOT EXISTS apps
(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS roles 
(
    id INTEGER PRIMARY KEY,
    is_admin BOOL NOT NULL,
    user_id INT NOT NULL UNIQUE,

    CONSTRAINT FOREIGN KEY(user_id) REFERENCES users(id)
);